###############################################################################
# BOOK  S E R V I C E    (replicas = 1 because of circuit‑breaker state)
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-svc
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels: { app: book-svc }
  template:
    metadata:
      labels:
        app: book-svc
    spec:
      containers:
        - name: book
          image: docker.io/bachyy/book-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              value: "b-1.mymsk:9092,b-2.mymsk:9092,b-3.mymsk:9092"
            - name: KAFKA_USERNAME
              valueFrom:
                { secretKeyRef: { name: msk-credentials, key: username } }
            - name: KAFKA_PASSWORD
              valueFrom:
                { secretKeyRef: { name: msk-credentials, key: password } }
            - name: DB_HOST
              value: bookstore-db-dev.cluster-c3ooo02mmam7.us-east-1.rds.amazonaws.com
            - name: DB_USER
              valueFrom:
                { secretKeyRef: { name: db-credentials, key: username } }
            - name: DB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: db-credentials, key: password } }
            - name: DB_NAME
              value: booksdb
            - name: RECOMMENDER_BASE_URL
              value: http://recommender-svc
          volumeMounts:
            - name: cb-state
              mountPath: /var/circuit
          livenessProbe:
            httpGet: { path: /status, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: cb-state
          emptyDir: {}
