###############################################################################
# CUSTOMER  S E R V I C E
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-svc
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels: { app: customer-svc }
  template:
    metadata:
      labels:
        app: customer-svc
    spec:
      containers:
        - name: customer
          image: docker.io/bachyy/customer-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              value: "3.129.102.184:9092,18.118.230.221:9093,3.130.6.49:9094"
            - name: DB_HOST
              value: bookstore-db-dev.cluster-cbd2qfc15yog.us-east-1.rds.amazonaws.com
            - name: DB_USER
              valueFrom:
                { secretKeyRef: { name: db-credentials, key: username } }
            - name: DB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: db-credentials, key: password } }
            - name: DB_NAME
              value: bookstore
          livenessProbe:
            httpGet: { path: /status, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
