apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-svc
  namespace: bookstore-ns
spec:
  replicas: 1
  selector: { matchLabels: { app: crm-svc } }
  template:
    metadata: { labels: { app: crm-svc } }
    spec:
      containers:
        - name: crm
          image: docker.io/bachyy/crm-svc:v1
          imagePullPolicy: Always
          env:
            - name: ANDREW_ID
              value: "ahmedc"
            - name: KAFKA_BROKERS
              value: "3.129.102.184:9092,18.118.230.221:9093,3.130.6.49:9094"
            - name: SMTP_HOST
              valueFrom: { secretKeyRef: { name: smtp-credentials, key: host } }
            - name: SMTP_PORT
              valueFrom: { secretKeyRef: { name: smtp-credentials, key: port } }
            - name: SMTP_USER
              valueFrom:
                { secretKeyRef: { name: smtp-credentials, key: username } }
            - name: SMTP_PASS
              valueFrom:
                { secretKeyRef: { name: smtp-credentials, key: password } }
