apiVersion: v1
kind: Service
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: web-bff
  ports:
    - port: 80 # external LB port
      targetPort: 80 # containerPort inside the pod
