apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels: { app: web-bff }
  template:
    metadata:
      labels: { app: web-bff }
    spec:
      containers:
        - name: web-bff
          image: «ECR_URI»/web-bff:latest
          ports:
            - containerPort: 80
          env:
            - name: BOOK_SERVICE_URL
              value: http://book-svc
            - name: CUSTOMER_SERVICE_URL
              value: http://customer-svc
          livenessProbe:
            httpGet: { path: /status, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
